### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by LionHackerman** [Spuckwaffel/UEDumper#15]
Hello. I was just wondering what the difference is between your dumper and [Dumper-7](https://github.com/Encryqed/Dumper-7). I see Dumper 7 doesn't require you to find offsets while this one does.

**Comment by Spuckwaffel** [comment]
Hey there, you would see the difference if you actually used both projects.
Dumper-7 is a internal dumping tool, you need to inject it into the target process. It also just dumps the SDK, it does not have
- a editor
- live editor
- overriding certain members in structs/classes
- overriding certain structs/classes
- dumps host (dumpspace) support
- project saving
and more.
Dumper-7 is only a dumper, but a pretty good dumper that's actively in development. You can't compare these two projects as the focus of my project is not only generating a SDK like Dumper-7. 
I doesn't need offsets because it tries to find these offsets. I didn't implement that because it's harder to do so externally and i don't see a issue with browsing the game dump for 2 minutes for offsets.
